name: Shuttle Deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
          secrets: |
            AUTHORIZED_EMAILS = '${{ secrets.AUTHORIZED_EMAILS }}'
            AUTH_PRIVATE_KEY = '${{ secrets.AUTH_PRIVATE_KEY }}'
            SENDGRID_API_KEY = '${{ secrets.SENDGRID_API_KEY }}'
